### PR TITLE
Update readme/namespaces

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis (VMware) <alexellis2@gmail.com>

## What

* Updates references to faas to OpenFaaS

* Clarifies Rancher 1.0, not Rancher 2.0 linking to the K8s provider

* Adds status of project

* Updates namespaces to correct placement on GitHub

* Updated Docker build to Go 1.10.4 and latest Alpine image to ship in

## Verification

Docker builds 👍 Tests pass :+1:

### CODE REVIEW

**Comment by kenfdev** [comment]
Thanks for the change Alex! One thing. I think it's better to say `Rancher 1.x` rather than `Rancher 1.0` because the majority is using Rancher 1.6. Same as to `Rancher 2.0`. The majority is using `Rancher 2.1` so how about `Rancher 2.x`?
Other than that, it looks great and thanks for the maintenance comment.

**Review by kenfdev — COMMENTED** [review]
Thanks for the change Alex! One thing. I think it's better to say Rancher 1.x rather than Rancher 1.0 because the majority is using Rancher 1.6. Same as to Rancher 2.0. The majority is using Rancher 2.1 so how about Rancher 2.x?
Other than that, it looks great and thanks for the maintenance comment.

**Comment by alexellis** [comment]
I think that makes sense :+1:

Alex

**Comment by kenfdev** [comment]
I can continue the edit about the version number but is that okay with you Alex?
Or I can wait your commit. Thank you!

**Comment by alexellis** [comment]
I'll merge so you can contribute the change.

**Pull request merged**
